name: CI

on: push

jobs:
  main:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Setup Project
        run: make setup

      - name: Test
        run: make test
